In [2]:
import numpy as np

In [78]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]], dtype=int)
print(a[0:2]) # Indexing
print(a[0:2, 1:3]) # Slicing

[[1 2 3]
 [4 5 6]]
2


In [6]:
a.shape = (1, 9)
print(a)

[[1 2 3 4 5 6 7 8 9]]


In [46]:
np.empty((3, 3), dtype=int) # Creates a 3x3 array of random integers

None


In [7]:
b = np.arange(24)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [43]:
np.linspace(2, 32, 17) # Creates an array of 17 evenly spaced numbers between 2 and 32

array([ 2.   ,  3.875,  5.75 ,  7.625,  9.5  , 11.375, 13.25 , 15.125,
       17.   , 18.875, 20.75 , 22.625, 24.5  , 26.375, 28.25 , 30.125,
       32.   ])

In [57]:
c = np.empty((3, 3), dtype=int)
c.sort()
print(c)

[[                  0                   0                   0]
 [                  0                   0 8319683848551211643]
 [3180222411935070754 7959390389040738153 8391722768137527840]]


In [58]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
print(np.concatenate((a, b))) # Concatenates two arrays

[1 2 3 4 5 6 7 8]


In [12]:
print(b.reshape(3, 8))

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]]


In [68]:
a = np.array([1, 2, 3, 4, 5, 6])
print(f'Before: {a} with shape: {a.shape}')
a2 = a[np.newaxis, :] # Adds a new axis
print(f'After: {a2} with shape: {a2.shape}')


Before: [1 2 3 4 5 6] with shape: (6,)
After: [[1 2 3 4 5 6]] with shape: (1, 6)


In [76]:
sample = np.arange(100)
print(sample[(sample>50) & (sample<70)])

[51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69]


In [80]:
np.random.default_rng().random((3, 3)) # Creates a 3x3 array of random numbers

array([[0.18308248, 0.29717371, 0.07841589],
       [0.99875212, 0.83491329, 0.63796383],
       [0.72722775, 0.10501782, 0.42732369]])

In [118]:
x = np.random.randn(3, 3) # Creates a 3x3 array of random numbers with normal distribution
print(x.flatten()) # Flattens the array
print(x.ravel()) # Flattens the array, but doesn't remove the reference to the original array
print(x)

[ 0.68981816  1.30184623 -0.62808756 -0.48102712  2.3039167  -1.06001582
 -0.1359497   1.13689136  0.09772497]
[ 0.68981816  1.30184623 -0.62808756 -0.48102712  2.3039167  -1.06001582
 -0.1359497   1.13689136  0.09772497]
[[ 0.68981816  1.30184623 -0.62808756]
 [-0.48102712  2.3039167  -1.06001582]
 [-0.1359497   1.13689136  0.09772497]]


In [109]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
print(np.unique(a)) # Returns the unique elements of an array. (Removes repatative elements)

[11 12 13 14 15 16 17 18 19 20]


In [111]:
a = np.array([1, 2, 3, 4, 5, 6])
print(np.flip(a) == a[::-1])

[ True  True  True  True  True  True]
