In [2]:
import numpy as np

In [3]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]], dtype=int)
print(a[0:2]) # Indexing
print(a[0:2, 0:1]) # Slicing

[[1 2 3]
 [4 5 6]]
[[1]
 [4]]


In [4]:
# a.shape = (1, 9)
# print(a)

In [5]:
np.empty((3, 3), dtype=int) # Creates a 3x3 array of random integers

array([[            33452368,                    0,             34041184],
       [-4475418130700891784,      140004050966320,             34045200],
       [-2572916757574923365,      140004050985648,                   80]])

In [6]:
b = np.arange(24)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [7]:
np.linspace(2, 32, 17) # Creates an array of 17 evenly spaced numbers between 2 and 32

array([ 2.   ,  3.875,  5.75 ,  7.625,  9.5  , 11.375, 13.25 , 15.125,
       17.   , 18.875, 20.75 , 22.625, 24.5  , 26.375, 28.25 , 30.125,
       32.   ])

In [8]:
c = np.empty((3, 3), dtype=int)
c.sort()
print(c)

[[                   0             44065392      140004045461968]
 [-8140523367342386326      140004045462112      140004046341504]
 [-4285249164764996544                   80      140004046341424]]


In [9]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
print(np.concatenate((a, b))) # Concatenates two arrays

[1 2 3 4 5 6 7 8]


In [10]:
# print(b.reshape(3, 8))

In [11]:
a = np.array([1, 2, 3, 4, 5, 6])
print(f'Before: {a} with shape: {a.shape}')
a2 = a[np.newaxis, :] # Adds a new axis
print(f'After: {a2} with shape: {a2.shape}')


Before: [1 2 3 4 5 6] with shape: (6,)
After: [[1 2 3 4 5 6]] with shape: (1, 6)


In [12]:
sample = np.arange(100)
print(sample[(sample>50) & (sample<70)])

[51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69]


In [13]:
np.random.default_rng().random((3, 3)) # Creates a 3x3 array of random numbers

array([[0.52148215, 0.394907  , 0.53333937],
       [0.35875577, 0.14048689, 0.97146367],
       [0.2669074 , 0.91765505, 0.41089116]])

In [14]:
x = np.random.randn(3, 3) # Creates a 3x3 array of random numbers with normal distribution
print(x.flatten()) # Flattens the array
print(x.ravel()) # Flattens the array, but doesn't remove the reference to the original array
print(x)

[-0.41918488  0.38595725 -0.61764116 -2.28489586  0.66513571  0.11217201
 -1.3765787  -3.81069597 -0.89202743]
[-0.41918488  0.38595725 -0.61764116 -2.28489586  0.66513571  0.11217201
 -1.3765787  -3.81069597 -0.89202743]
[[-0.41918488  0.38595725 -0.61764116]
 [-2.28489586  0.66513571  0.11217201]
 [-1.3765787  -3.81069597 -0.89202743]]


In [15]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
print(np.unique(a)) # Returns the unique elements of an array. (Removes repatative elements)

[11 12 13 14 15 16 17 18 19 20]


In [16]:
a = np.array([1, 2, 3, 4, 5, 6])
print(np.flip(a) == a[::-1])

[ True  True  True  True  True  True]


In [17]:
fk = np.array([[[ 8.46185607e-02, 9.96004954e-01, 2.85277144e-02, 8.51759965e-02], 
 [ 2.35438658e-03, 2.84304598e-02 -9.99593000e-01, 2.45003129e-03], 
 [-9.96410636e-01, 8.46512863e-02, 6.07638895e-05, 6.48279712e-01], 
 [ 0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.00000000e+00], ]])

/tmp/ipykernel_339/1277898651.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  fk = np.array([[[ 8.46185607e-02, 9.96004954e-01, 2.85277144e-02, 8.51759965e-02],


In [18]:
fk
# position = np.array([fk[0][3], fk[1][3], fk[2][3]])

array([[list([0.0846185607, 0.996004954, 0.0285277144, 0.0851759965]),
        list([0.00235438658, -0.9711625401999999, 0.00245003129]),
        list([-0.996410636, 0.0846512863, 6.07638895e-05, 0.648279712]),
        list([0.0, 0.0, 0.0, 1.0])]], dtype=object)

In [19]:
np.array([[[[]]]]).ndim # In numpy, dimensions are called axes. The number of axes is rank. The shape of an array is a tuple of integers giving the size of the array along each axis.

4

In [20]:
np.empty(((5, 2, 3)), dtype=int) # Creates a 5x2x3 array of random integers

array([[[       35286096,               0, 140003994405104],
        [140004066764336, 140003994405040, 140004066764336]],

       [[140003994404976, 140004066764336, 140003994404784],
        [140004066764336, 140003994404912, 140004066764336]],

       [[140003994404848, 140004066764336, 140003994404656],
        [140004066764336, 140003994404720, 140004066764336]],

       [[140003994404592, 140003994403568, 140004068542064],
        [140004066764336, 140004068542064, 140003994404400]],

       [[140004068542064, 140004066764336, 140004068542064],
        [140003994403824, 140004068542064, 140004066764336]]])

In [21]:
a = np.array([1, 2, 3])
print(f"array: {a}, shape: {a.shape},  ndim: {a.ndim}")

a = a[:, np.newaxis]
print(f"array: {a}, shape: {a.shape},  ndim: {a.ndim}")

a = a[:, np.newaxis]
print(f"array: {a}, shape: {a.shape},  ndim: {a.ndim}")

a = a[:, np.newaxis]
print(f"array: {a}, shape: {a.shape},  ndim: {a.ndim}")

array: [1 2 3], shape: (3,),  ndim: 1
array: [[1]
 [2]
 [3]], shape: (3, 1),  ndim: 2
array: [[[1]]

 [[2]]

 [[3]]], shape: (3, 1, 1),  ndim: 3
array: [[[[1]]]


 [[[2]]]


 [[[3]]]], shape: (3, 1, 1, 1),  ndim: 4


In [22]:
b = np.arange(48)
print(b)
c = b = b.reshape(2, 4, 3, 2)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47]
[[[[ 0  1]
   [ 2  3]
   [ 4  5]]

  [[ 6  7]
   [ 8  9]
   [10 11]]

  [[12 13]
   [14 15]
   [16 17]]

  [[18 19]
   [20 21]
   [22 23]]]


 [[[24 25]
   [26 27]
   [28 29]]

  [[30 31]
   [32 33]
   [34 35]]

  [[36 37]
   [38 39]
   [40 41]]

  [[42 43]
   [44 45]
   [46 47]]]]


In [23]:
c[c < 10] # It flattens first!

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
c[c % 5 == 3]

array([ 3,  8, 13, 18, 23, 28, 33, 38, 43])

In [25]:
c[(c % 3 == 1) & (c % 2 == 0)]

array([ 4, 10, 16, 22, 28, 34, 40, 46])

In [26]:
(c % 3 == 1) & (c % 2 == 0)

array([[[[False, False],
         [False, False],
         [ True, False]],

        [[False, False],
         [False, False],
         [ True, False]],

        [[False, False],
         [False, False],
         [ True, False]],

        [[False, False],
         [False, False],
         [ True, False]]],


       [[[False, False],
         [False, False],
         [ True, False]],

        [[False, False],
         [False, False],
         [ True, False]],

        [[False, False],
         [False, False],
         [ True, False]],

        [[False, False],
         [False, False],
         [ True, False]]]])

In [27]:
c < 10

array([[[[ True,  True],
         [ True,  True],
         [ True,  True]],

        [[ True,  True],
         [ True,  True],
         [False, False]],

        [[False, False],
         [False, False],
         [False, False]],

        [[False, False],
         [False, False],
         [False, False]]],


       [[[False, False],
         [False, False],
         [False, False]],

        [[False, False],
         [False, False],
         [False, False]],

        [[False, False],
         [False, False],
         [False, False]],

        [[False, False],
         [False, False],
         [False, False]]]])

In [28]:
d = np.array([[1, 2, 3], [4, 5, 6]])
np.square(d)

array([[ 1,  4,  9],
       [16, 25, 36]])

In [29]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[7, 8, 9], [10, 11, 12], [13, 14, 15]])

C = np.matmul(A, B)

print(C)

[[ 66  72  78]
 [156 171 186]
 [246 270 294]]


In [30]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c = np.dot(a, b)

print(c)

32


In [31]:
x = int(5)

In [32]:
x

5

In [33]:
y = float(2.8)

In [34]:
y

2.8

In [35]:
print(type(x))

<class 'int'>


In [36]:
'hello'.upper()

'HELLO'

In [55]:
arr = np.array([1,4,3,4,5,4,4])

In [49]:
arr.shape

(7,)

In [56]:
np.where(arr == 4)

(array([1, 3, 5, 6]),)

In [57]:
arr.sort()

In [58]:
arr

array([1, 3, 4, 4, 4, 4, 5])

In [66]:
arr = np.array([1,2,3])
print(np.cumsum(arr))

[1 3 6]
